default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['SHELKOVOD_DB_HOST'] %>
  username: <%= ENV['SHELKOVOD_USER'] %>
  password: <%= ENV['SHELKOVOD_PASS'] %>
  
development:
  <<: *default
  database: <%= ENV['SHELKOVOD_DEV_DB'] %>

test:
  <<: *default
  database: <%= ENV['SHELKOVOD_TEST_DB'] %>

production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  database: <%= ENV['SHELKOVOD_PROD_DB'] %>

